packageExtensions:
  "ts-loader@*":
    dependencies:
      webpack: "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
      "@angular/cli": "*"
    peerDependencies:
      eslint: "*"
      typescript: "*"


yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: "node-modules"
