nodeLinker: node-modules

packageExtensions:
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
      "@angular/cli": "*"
    peerDependencies:
      eslint: "*"
      typescript: "*"
  ts-loader@*:
    dependencies:
      webpack: ^5.76.0
  cosmiconfig-typescript-loader@*:
    dependencies:
      "@types/node": "*"
  "@nx/devkit@*":
    dependencies:
      "nx": ^15.9.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
