export type { IProduct as IProductKs } from './product.interface'
export type { ICategory as ICategoryKs } from './category.interface'
export type { IDocument as IDocumentKs } from './document.interface'
export type { IEmployee as IEmployeeKs } from './employee.interface'
export type { IStore as IStoreKs } from './store.interface'
export type { IUom as IUomKs } from './uom.interface'
